### ISSUE TITLE
InstallError

### ISSUE THREAD

**Issue by B1991ing** [a-h-b/binny#58]
Dear Oskar,

I am trying to install the binny on another HPC platform now. But, I had another kind of error as shown in the screenshot.
![image](https://github.com/a-h-b/binny/assets/155892166/fb4a6ad4-db1b-4456-b794-2acde753b292)

Before asking you, I already checked **the content of .condarc** under my own directory (On this HPC platform, only one personal directory for each HPC user, so people can install and save everything here).
[condarc.txt](https://github.com/a-h-b/binny/files/14420391/condarc.txt)

envs_dirs:
  - ~/conda_envs
 
pkgs_dirs:
  - ~/conda_pkgs

I only loaded **the latest version of conda** in VARIABLE_CONFIG.
[VARIABLE_CONFIG.txt](https://github.com/a-h-b/binny/files/14420462/VARIABLE_CONFIG.txt)

No change in the file config/config.init.yaml.

Looking forward for your help.

Thank you very much.

Best,

Bing

**Comment by ohickl** [comment]
Sorry Bing,
totally missed this! Ill check if I can reproduce asap!

**Comment by ohickl** [comment]
in the meantime you can also try the conda beta version.
you can install it e.g. with:
 `micromamba create --prefix <path/to/my>/local_tools/binny bioconda::binny`.
Then you just run:
```
binny_path="<path/to/my>/local_tools/binny"
# Activate binny environment
micromamba activate ${binny_path}
# Ensure its all setup
binny --setup > binny_setup.log 2>&1
# Run a test
test_data_dir="${binny_path}/lib/python3.10/site-packages/binny/test"
binny --assembly ${test_data_dir}/contigs_4bins.fa \
      --bam ${test_data_dir}/*.bam \
      --outputdir ${test_data_dir}/out > binny_test.log 2>&1
```

**Comment by B1991ing** [comment]
Thank you very much for your reply, Oskar.

I got an error when installation --- **PackageNotFoundError: Packages missing in current channels:**

**Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - bioconda::binny

We have searched for the packages in the following channels:
            
  - http://localhost/anaconda/pkgs/main/linux-64
  - http://localhost/anaconda/pkgs/main/noarch
  - http://localhost/anaconda/pkgs/free/linux-64
  - http://localhost/anaconda/pkgs/free/noarch
  - http://localhost/anaconda/pkgs/r/linux-64
  - http://localhost/anaconda/pkgs/r/noarch
  - http://localhost/anaconda/cloud/conda-forge/linux-64
  - http://localhost/anaconda/cloud/conda-forge/noarch
  - http://localhost/anaconda/cloud/bioconda/linux-64
  - http://localhost/anaconda/cloud/bioconda/noarch**
  
How to solve it according to your experience?

I installed binny in the same PC but using two HPC accounts, one is successful and another is failed.

Best,

Bing

**Comment by B1991ing** [comment]
Hi Oskar,

I ran the test on the HPC account that successfully installed by me, but an error happened as shown below.

**ModuleNotFoundError: No module named 'Resources.UniFunc.unifunc'**

[binny_setup.log](https://github.com/a-h-b/binny/files/14896531/binny_setup.log)
[binny_test.log](https://github.com/a-h-b/binny/files/14896532/binny_test.log)


Best,

Bing

**Comment by ohickl** [comment]
Hey, the setup error is strange:
```
fatal: unable to access 'https://github.com/PedroMTQ/UniFunc.git/': Could not resolve host: github.com
```
that sounds like you were lacking access to the github site/internet for some reason? maybe a temporary problem?
the error during the test was my bad, i had a typo in my example command (`|` instead of `\`  in the `--bam` line), i fixed it.
maybe you can just retry?

**Comment by B1991ing** [comment]
> the error during the test was my bad, i had a typo in my example command (`|` instead of `\` in the `--bam` line), i fixed it.
> maybe you can just retry?

Oskar, can you tell me where is the typo in the --bam line ?

**Comment by B1991ing** [comment]
still not okay now.
I ran as shown below,
module load conda-mirror
conda create --prefix local_tools/binny bioconda::binny

binny_path="./local_tools/binny"
# Activate binny environment
conda activate ${binny_path}
# Ensure its all setup
binny --setup > binny_setup.log 2>&1
# Run a test
test_data_dir="${binny_path}/lib/python3.9/site-packages/binny/test"
binny --assembly ${test_data_dir}/contigs_4bins.fa \
      --bam ${test_data_dir}/*.bam \
      --outputdir ${test_data_dir}/out > binny_test.log 2>&1

**Comment by ohickl** [comment]
> > the error during the test was my bad, i had a typo in my example command (`|` instead of `\` in the `--bam` line), i fixed it.
> > maybe you can just retry?
> 
> Oskar, can you tell me where is the typo in the --bam line ?

It was this line `--bam ${test_data_dir}/*.bam \` before it was `--bam ${test_data_dir}/*.bam |` it is already corrected in the previous response.

Regarding your new attempt, is it still the same error?

**Comment by B1991ing** [comment]
> --bam ${test_data_dir}/*.bam \

Still same error. I ran using the corrected version, but not work.

binny --assembly ${test_data_dir}/contigs_4bins.fa \
      --bam ${test_data_dir}/*.bam \
      --outputdir ${test_data_dir}/out > binny_test.log 2>&1

**Comment by ohickl** [comment]
strange, i just tried again with no problems:
```
> micromamba activate ${binny_path}
> binny --setup
Cloning into '/mnt/lscratch/users/ohickl/local_tools/binny/lib/python3.10/site-packages/Resources/UniFunc'...
remote: Enumerating objects: 224, done.
remote: Total 224 (delta 0), reused 0 (delta 0), pack-reused 224
Receiving objects: 100% (224/224), 24.10 MiB | 20.43 MiB/s, done.
Resolving deltas: 100% (111/111), done.
...
```
Can you try, with the binny env activated:
`mantis  check` or `mantis db`. It will probably fail at some later stage, but do you get the same error?
If so, there might be a problem with your cluster accounts/clusters internet access?

**Comment by B1991ing** [comment]
> Can you try, with the binny env activated:
> `mantis check` or `mantis db`. It will probably fail at some later stage, but do you get the same error?
> If so, there might be a problem with your cluster accounts/clusters internet access?

**The NWAFU HPC cluster which I am using now can't be connected with any internet.**

I tried command lines - **mantis check or mantis db** with the binny env activated. Bur same error happened.

binny_path="./local_tools/binny"
# Activate binny environment
conda activate ${binny_path}

**mantis check** 
<img width="901" alt="截屏2024-04-11 09 28 10" src="https://github.com/a-h-b/binny/assets/155892166/ed7c044b-3c49-4cdd-8624-f34ee794ba6c">

 **mantis db**
<img width="888" alt="截屏2024-04-11 09 28 31" src="https://github.com/a-h-b/binny/assets/155892166/fa597f7d-49ad-4090-8a01-8243008b8d0e">

**Comment by B1991ing** [comment]
> strange, i just tried again with no problems:

I installed **miniconda3** on my HPC folder, so I used **conda create**, **conda activate**.

module load conda-mirror
conda create --prefix ./local_tools/binny bioconda::binny

binny_path="./local_tools/binny"
# Activate binny environment
conda activate ${binny_path}
# Ensure its all setup
/storage/public/home/2023110148/local_tools/binny/bin/binny --setup > /storage/public/home/2023110148/local_tools/binny/binny_setup.log 2>&1
# Run a test
test_data_dir="${binny_path}/lib/python3.10/site-packages/binny/test"
/storage/public/home/2023110148/local_tools/binny/bin/binny --assembly ${test_data_dir}/contigs_4bins.fa \
      --bam ${test_data_dir}/*.bam \
      --outputdir ${test_data_dir}/out > /storage/public/home/2023110148/local_tools/binny/binny_test.log 2>&1

**Comment by ohickl** [comment]
> > Can you try, with the binny env activated:
> > `mantis check` or `mantis db`. It will probably fail at some later stage, but do you get the same error?
> > If so, there might be a problem with your cluster accounts/clusters internet access?
> 
> **The NWAFU HPC cluster which I am using now can't be connected with any internet.**

Hm, but then can you even successfully install the binny env?

It also says you dont have the mantis `Multiprocessing` module for the `mantis ...` tests, which you definitely should have, if the environment install worked properly.

I am not sure what the problem is. Can you maybe check again with one of your sys admins? or maybe a colleague can also try the installation, to see if it is a general problem.

**Comment by B1991ing** [comment]
> Hm, but then can you even successfully install the binny env?
> 
> It also says you dont have the mantis `Multiprocessing` module for the `mantis ...` tests, which you definitely should have, if the environment install worked properly.
> 
> I am not sure what the problem is. Can you maybe check again with one of your sys admins? or maybe a colleague can also try the installation, to see if it is a general problem.

One thing is that if I installed miniconda, do I need to **module load conda-mirror** on HPC when installing binny?

**Comment by ohickl** [comment]
i dont think so. what conda version does `conda-mirror` load? i would go with mamba as a much faster, still easy to use variant.

**Comment by B1991ing** [comment]
> i dont think so. what conda version does `conda-mirror` load? i would go with mamba as a much faster, still easy to use variant.

Hi Oskar, I don't have micromamba, so I tried 
**mamba create --prefix binny bioconda::binny**
But, I got error at the end.
<img width="819" alt="截屏2024-04-17 21 39 25" src="https://github.com/a-h-b/binny/assets/155892166/9e7903f6-32ae-4a48-beaa-37fc822f392f">

Best,

Bing

**Comment by B1991ing** [comment]
> > i dont think so. what conda version does `conda-mirror` load? i would go with mamba as a much faster, still easy to use variant.
> 
> Hi Oskar, I don't have micromamba, so I tried **mamba create --prefix binny bioconda::binny** But, I got error at the end. <img alt="截屏2024-04-17 21 39 25" width="819" src="https://private-user-images.githubusercontent.com/155892166/323239647-9e7903f6-32ae-4a48-beaa-37fc822f392f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjE1NzMsIm5iZiI6MTcxMzM2MTI3MywicGF0aCI6Ii8xNTU4OTIxNjYvMzIzMjM5NjQ3LTllNzkwM2Y2LTMyYWUtNGE0OC1iZWFhLTM3ZmM4MjJmMzkyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMzQxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDkzNTI3MDM4ODcxY2MzY2EyZDM0NGQxNjRhZGYzMjIyNWMyZTczODYxZTNlY2MyN2IyZTgxYTIxNDM5NDVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q8SwxZdJSMtWzZYM3kOfni5-FqDassJq4j3rLX08j0Y">
> 
> Best,
> 
> Bing

I changed to another linux server, now this linux operation can connect to GitHub.
